version: '3'
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      container_name: ml_zoomcamp
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
#        - ${LOCAL_DATASETS}:/home/jovyan/work/data
#        - ${LOCAL_MODELS}:/home/jovyan/work/models
#        - ${LOCAL_HOMEWORK}:/home/jovyan/work/homework
#        - ${LOCAL_PRACTISE}:/home/jovyan/work/practise
      ports:
        - ${PORT}:8888
