version: '3'
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      container_name: jupyter_ml_zoomcamp
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
        - ${LOCAL_DATASETS}:/home/jovyan/work/data
        - ${LOCAL_MODELS}:/home/jovyan/work/models
      ports:
        - ${PORT}:8888
